# Java 中的异常处理：包含最佳和最差实践的完整指南



## 概述

在 Java 中处理异常是开发人员应该牢记的最基本和最基本的事情之一。遗憾的是，这常常被忽视，异常处理的重要性被低估了——它与代码的其余部分一样重要。

在本文中，我们将介绍您需要了解的有关 Java 异常处理的所有信息，以及好的和坏的做法。

## 异常层次结构

所有这*一切都*引出了一个问题——*在 Java 和 JVM 眼中，这些异常是什么？*

毕竟，例外只是扩展`Throwable`接口的Java 对象：

![1637042352570](异常.assets/1637042352570.png)

当我们谈论特殊情况时，我们通常指的是以下三种情况之一：

- 检查异常
- 未经检查的异常/运行时异常
- 错误

**注意**：术语“运行时”和“未检查”经常互换使用，指的是同一种异常。

### Checked Exceptions

检查异常是 Java 编译器要求我们处理的异常。我们要么声明性地将异常抛出调用堆栈，要么我们必须自己处理它。稍后将详细介绍这两者。

[Oracle 的文档](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html)告诉我们当我们可以合理地期望我们的方法的调用者能够恢复时使用检查异常。

检查异常的几个例子是*IOException*和 *ServletException。*



###  Unchecked Exceptions

未经检查的异常是 Java 编译器不需要我们处理的异常。

简单地说，如果我们创建一个扩展 RuntimeException 的异常，它就会被取消检查；否则，它将被检查。

虽然这听起来很方便，但 Oracle 的文档告诉我们这两个概念都有很好的理由，比如区分情境错误（已检查）和使用错误（未检查）。

未经检查的异常的一些示例是 NullPointerException、IllegalArgumentException 和 SecurityException。



### Errors

错误代表严重且通常无法恢复的情况，例如库不兼容、无限递归或内存泄漏。

即使它们没有扩展 *RuntimeException*，它们也没有被检查。


  在大多数情况下，我们处理、实例化或扩展*Errors*会很奇怪 。通常，我们希望这些一直向上传播。

几个错误示例是 *StackOverflowError*和 *OutOfMemoryError*。



## 如何处理异常

在 Java API 中，有很多地方可能会出错，其中一些地方标有异常，无论是在签名中还是在 Javadoc 中

```java
/**
 * @exception FileNotFoundException ...
 */
public Scanner(String fileName) throws FileNotFoundException {
   // ...
}
```

如前所述，当我们调用这些“有风险”的方法时，我们必须处理已检查的异常，而我们可能会处理未检查的异常。 Java 为我们提供了几种方法来做到这一点：



###  **throws**

“处理”异常的最简单方法是重新抛出它：

```java
public int getPlayerScore(String playerFile)
  throws FileNotFoundException {
 
    Scanner contents = new Scanner(new File(playerFile));
    return Integer.parseInt(contents.nextLine());
}
```

因为 FileNotFoundException 是一个检查过的异常，这是满足编译器的最简单的方法，但这意味着任何调用我们方法的人现在也需要处理它

parseInt可以抛出一个NumberFormatException，但是因为它是未检查的，我们不需要处理它。



###  **try-catch**

如果我们想自己尝试处理异常，我们可以使用 try-catch 块。我们可以通过重新抛出异常来处理它：

```java
public int getPlayerScore(String playerFile) {
    try {
        Scanner contents = new Scanner(new File(playerFile));
        return Integer.parseInt(contents.nextLine());
    } catch (FileNotFoundException noFile) {
        throw new IllegalArgumentException("File not found");
    }
}
```

或者通过执行恢复步骤：

```java
public int getPlayerScore(String playerFile) {
    try {
        Scanner contents = new Scanner(new File(playerFile));
        return Integer.parseInt(contents.nextLine());
    } catch ( FileNotFoundException noFile ) {
        logger.warn("File not found, resetting score.");
        return 0;
    }
}
```



### **finally**

现在，有时无论是否发生异常，我们都需要执行代码，这就是 finally 关键字的用武之地。

到目前为止，在我们的示例中，隐藏着一个令人讨厌的错误，即默认情况下 Java 不会将文件句柄返回给操作系统。

当然，无论我们是否可以读取文件，我们都希望确保我们进行了适当的清理！

让我们先试试这个“懒惰”的方法：

```java
public int getPlayerScore(String playerFile)
  throws FileNotFoundException {
    Scanner contents = null;
    try {
        contents = new Scanner(new File(playerFile));
        return Integer.parseInt(contents.nextLine());
    } finally {
        if (contents != null) {
            contents.close();
        }
    }
}
```

在这里，finally块指出了我们希望Java运行的代码，无论试图读取文件的过程发生了什么。

即使在调用堆栈中抛出了FileNotFoundException，Java也会在这之前调用Final的内容。



我们也可以既处理异常又确保我们的资源被关闭。

```java
public int getPlayerScore(String playerFile) {
    Scanner contents;
    try {
        contents = new Scanner(new File(playerFile));
        return Integer.parseInt(contents.nextLine());
    } catch (FileNotFoundException noFile ) {
        logger.warn("File not found, resetting score.");
        return 0; 
    } finally {
        try {
            if (contents != null) {
                contents.close();
            }
        } catch (IOException io) {
            logger.error("Couldn't close the reader!", io);
        }
    }
}
```

因为 close 也是一种“有风险”的方法，我们也需要捕捉它的异常！

这可能看起来很复杂，但我们需要每个部分来处理可能正确出现的每个潜在问题。



### *try-with-resources* Statement

The previously complex and verbose block can be substituted with:

```java
static String readFirstLineFromFile(String path) throws IOException {
    try(BufferedReader br = new BufferedReader(new FileReader(path))) {
        return br.readLine();
    }
}
```

It's much cleaner and it's obviously simplified by including the declaration within the parentheses of the `try` block.

Additionally, you can include multiple resources in this block, one after another:

```java
static String multipleResources(String path) throws IOException {
    try(BufferedReader br = new BufferedReader(new FileReader(path));
        BufferedWriter writer = new BufferedWriter(path, charset)) {
        // some code
    }
}
```

This way, you don't have to concern yourself with closing the resources yourself, as the *try-with-resources* block ensures that the resources will be closed upon the end of the statement.



### Multiple *catch* Blocks

When the code we're writing can throw more than one exception, we can employ several catch blocks to handle them individually:

```java
public void parseFile(String filePath) {
    try {
        // some code 
    } catch (IOException ex) {
        // handle
    } catch (NumberFormatException ex) {
        // handle
    }
}
```





## **常见异常和错误**

### **检查异常**

- *IOException* – 此异常通常表示网络、文件系统或数据库上的某些内容失败。

###  **运行时异常**

- *ArrayIndexOutOfBoundsException——*这个异常意味着我们试图访问一个不存在的数组索引，就像试图从一个长度为 3 的数组中获取索引 5 一样。
- *ClassCastException –*这个异常意味着我们试图执行非法转换，比如尝试将*String*转换为*List*。我们通常可以通过在转换前执行防御性*instanceof* 检查来避免它 。
- *IllegalArgumentException* - 此异常是我们说提供的方法或构造函数参数之一无效的通用方式。
- *IllegalStateException* – 此异常是我们说我们的内部状态（如对象的状态）无效的通用方式。
- *NullPointerException* – 这个异常意味着我们试图引用一个*空*对象。我们通常可以通过执行防御性*空*检查或使用 *Optional*来避免它*。*
- *NumberFormatException* – 此异常意味着我们尝试将*String*转换为数字，但该字符串包含非法字符，例如尝试将“5f3”转换为数字。

### **错误**

- *StackOverflowError –* 此异常意味着堆栈跟踪太大。这有时会发生在大规模应用程序中；然而，这通常意味着我们的代码中发生了一些无限递归。

- *NoClassDefFoundError* – 此异常意味着类由于不在类路径上或由于静态初始化失败而无法加载。

- *OutOfMemoryError* – 此异常意味着 JVM 没有更多内存可用于为更多对象分配。有时，这是由于内存泄漏。

  

